# version: '3.8'
# services:
#   jobkorea_crawler:
#     build: ./crawler
#     container_name: jobkorea_crawler
#     ports:
#       - "4040:5000"
#     environment:
#       - FLASK_APP=app.py  # app.py를 진입점으로 지정
#     command: ["python", "app.py"]

#   workent_crawler:
#     build: ./crawler
#     container_name: workent_crawler
#     ports:
#       - "4041:5000"
#     environment:
#       - FLASK_APP=app.py  # app.py를 진입점으로 지정
#     command: ["python", "app.py"]

#   saramin_crawler:
#     build: ./crawler
#     container_name: saramin_crwaler
#     ports:
#       - "4042:5000"
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_DEBUG=1
#       - SARAMIN_ACCESS_KEY="iE7rO0FJx5rPtiz6bVrHVGr4KEVBHYCWjSDAm2yWvKIUKB3GkG" # 실제 접근 키로 변경
#     command: ["python", "app.py"]


# version: '3.8'
# services:
#   jobkorea_crawler:
#     build: ./crawler
#     container_name: jobkorea_crawler
#     ports:
#       - "4040:5000"
#     environment:
#       - CRAWLER_TYPE=jobkorea
#     command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

#   worknet_crawler:
#     build: ./crawler
#     container_name: worknet_crawler
#     ports:
#       - "4041:5000"
#     environment:
#       - CRAWLER_TYPE=worknet
#     command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

#   crawler:
#     build: ./crawler
#     container_name: all_crawler
#     ports:
#       - "4042:5000"
#     environment:
#       - CRAWLER_TYPE=jobkorea,worknet,saramin
#       - SARAMIN_ACCESS_KEY=${SARAMIN_ACCESS_KEY}
#     command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

#   saramin_crawler:  
#     build: ./crawler
#     container_name: saramin_crawler  
#     ports:
#       - "4044:5000"
#     environment:
#       - CRAWLER_TYPE=saramin
#       - SARAMIN_ACCESS_KEY=${SARAMIN_ACCESS_KEY}
#     command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

services:
  all_crawler:
    build: ./crawler
    container_name: all_crawler
    ports:
      - "4042:5000"
    environment:
      - CRAWLER_TYPE=jobkorea,worknet,saramin
      - SARAMIN_ACCESS_KEY=${SARAMIN_ACCESS_KEY}
    command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

