services:
  all_crawler:
    build: ./crawler
    container_name: all_crawler
    ports:
      - "4042:5000"
    environment:
      - CRAWLER_TYPE=jobkorea,worknet,saramin
      - SARAMIN_ACCESS_KEY=${SARAMIN_ACCESS_KEY}
    command: ["uvicorn", "app:fast_app", "--host", "0.0.0.0", "--port", "5000"]

